# ==============================================================================
# Podman Storage Configuration
# ==============================================================================
#
# This file configures the storage driver for Podman.
# For more details, see the storage.conf documentation:
# https://github.com/containers/storage/blob/main/docs/storage.conf.5.md
#

[storage]
# The storage driver to use. "overlay" is the recommended driver for most
# modern Linux filesystems.
driver = "overlay"

[storage.options.overlay]
# Specifies the program to use for mounting overlay filesystems.
# Using "fuse-overlayfs" allows rootless Podman to function correctly
# inside a container.
mount_program = "/usr/bin/fuse-overlayfs"
